### ISSUE TITLE
json.decoder.JSONDecodeError: Invalid \escape: line 3 column 23 (char 87)

### ISSUE THREAD

**Issue by Sudge32** [mustafadalga/Instagram-Bot#15]
Hey there, I have this Problem before starting your bot: 

`Traceback (most recent call last):
  File "C:\Python\Instagram-Bot-master\instagram.py", line 2031, in <module>
    instagram = Instagram()
  File "C:\Python\Instagram-Bot-master\instagram.py", line 21, in __init__
    self.ayarlarYukle()
  File "C:\Python\Instagram-Bot-master\instagram.py", line 1040, in ayarlarYukle
    self.config = json.load(dosya)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 3 column 23 (char 87)`

Maybe you can help me? Thanks in advance

**Comment by mustafadalga** [comment]
An error occurs while loading the config.json file. Have you downloaded the config.json file properly. It may be due to a missing file.

what version of python you are using?
