### ISSUE TITLE
json.decoder.JSONDecodeError: Unexpected UTF-8 BOM

### ISSUE THREAD

**Issue by WhoR3born** [mustafadalga/Instagram-Bot#16]
getting this error

`Traceback (most recent call last):
  File "C:\Users\ASrosTOS\Desktop\Instagram-Bot-master\instagram.py", line 2031, in <module>
    instagram = Instagram()
  File "C:\Users\ASrosTOS\Desktop\Instagram-Bot-master\instagram.py", line 21, in __init__
    self.ayarlarYukle()
  File "C:\Users\ASrosTOS\Desktop\Instagram-Bot-master\instagram.py", line 1040, in ayarlarYukle
    self.config = json.load(dosya)
  File "C:\Users\ASrosTOS\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\ASrosTOS\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 335, in loads
    raise JSONDecodeError("Unexpected UTF-8 BOM (decode using utf-8-sig)",
json.decoder.JSONDecodeError: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)`

**Comment by mustafadalga** [comment]
Such an error may occur due to the terminal you are using.
Have you tried using Powershell?
