### ISSUE TITLE
Error after I run instagram.py

### ISSUE THREAD

**Issue by Doolitt** [mustafadalga/Instagram-Bot#29]
C:\Users\royal\Instagram-Bot>python -m instagram.py
Traceback (most recent call last):
  File "C:\Users\royal\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\royal\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\royal\Instagram-Bot\instagram.py", line 2036, in <module>
    instagram = Instagram()
  File "C:\Users\royal\Instagram-Bot\instagram.py", line 23, in __init__
    self.ayarlarYukle()
  File "C:\Users\royal\Instagram-Bot\instagram.py", line 1042, in ayarlarYukle
    self.config = json.load(dosya)
  File "C:\Users\royal\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Users\royal\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\royal\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\royal\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 3 column 23 (char 87)

**Comment by Doolitt** [comment]
I looked at a closed issue and saw the solution Thank you
